name: new-version
on:
  workflow_dispatch:
    inputs:
      version:
        description: version of the npm package you want to deploy
        required: true
        type: string
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 15
      - run: git checkout -b version/${{ github.event.inputs.version }}
      - run: git push --set-upstream origin origin
